### ISSUE TITLE
Query hangs in cluster mode

### ISSUE THREAD

**Issue by leiysky** [datafuselabs/databend#7280] opened 2022-08-24 12:25 UTC
Minimal reproduce:

```sql
create table t(a int);
insert into t values(1);
select * from t join numbers(5) on t.a = number;
```

Seems if the build side of hash join is a `numbers` table and probe side is a table created with fuse engine, the query will hang.

cc @zhang2014

**Comment by BohuTANG** [comment] 2022-08-24 12:34
I have tried an old version(Just FYI):
```
DatabendQuery v0.8.5-nightly-c4e444b-simd(rust-1.64.0-nightly-2022-08-22T16:28:19.155655958Z)

2-nodes the query returns:
1015: Cannot downcast from PartInfo to FusePartInfo. (while in processor thread 0)
```

**Comment by leiysky** [comment] 2022-08-24 13:09
> I have tried an old version(Just FYI):
> 
> ```
> DatabendQuery v0.8.5-nightly-c4e444b-simd(rust-1.64.0-nightly-2022-08-22T16:28:19.155655958Z)
> 
> 2-nodes the query returns:
> 1015: Cannot downcast from PartInfo to FusePartInfo. (while in processor thread 0)
> ```

I encountered this error before but cannot reproduce it now. It might be the root cause.

**Comment by BohuTANG** [comment] 2022-08-24 13:14
> > I have tried an old version(Just FYI):
> > ```
> > DatabendQuery v0.8.5-nightly-c4e444b-simd(rust-1.64.0-nightly-2022-08-22T16:28:19.155655958Z)
> > 
> > 2-nodes the query returns:
> > 1015: Cannot downcast from PartInfo to FusePartInfo. (while in processor thread 0)
> > ```
> 
> I encountered this error before but cannot reproduce it now. It might be the root cause.

You can reproduce it with v0.8.5 https://github.com/datafuselabs/databend/releases/tag/v0.8.5-nightly

**Comment by zhang2014** [comment] 2022-10-10 00:24
Can't reproduce, let's close it.

**Closed by zhang2014** 2022-10-10 00:24 UTC
Labels: C-bug
