### ISSUE TITLE
Alias not work: `select number as n from numbers(10) where n>10`

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4128] opened 2022-02-13 05:23 UTC
**Summary**

```
mysql> select number as n from numbers(10) where n>10;
ERROR 1105 (HY000): Code: 1058, displayText = Unknown column n.
```

**Comment by BohuTANG** [comment] 2022-02-13 05:25
Is this not support or it's a bug? cc @zhyass @sundy-li

**Comment by BohuTANG** [comment] 2022-02-13 05:47
I think it's a bug on alias with `where` here, `order by` with alias works well:
```
mysql> select number as n from numbers(10) order by n desc;
```

**Comment by sundy-li** [comment] 2022-02-13 07:13
It's not a bug. See:  https://github.com/datafuselabs/databend/blob/acc924fd890d73bac5860eacbea3f97e2c1d744c/docs/dev/rfcs/query/0002-plan-expression.md

We follow the standard SQL alias behavior.

**Comment by BohuTANG** [comment] 2022-02-13 09:41
Thanks for your information! @sundy-li 

This is a bit weird(feel this is useful for users), almost most SQL database(MySQL/ClickHouse/Snowflake, except **PostgreSQL**) supports this.
For example:
```
select 3*(number+1) as c1 from numbers(10) where c1 > 3;
```
I think we should support it for users not the standard.
Any thoughts? Also cc @leiysky

**Comment by sundy-li** [comment] 2022-02-13 11:25
@leiysky already explained it in  #1553

Closing this to there.

**Closed by sundy-li** 2022-02-13 11:25 UTC
Labels: C-bug, prio: high
