### ISSUE TITLE
When running `SELECT NULLIF(1, 1);` and `SELECT NULLIF('a', 'a');`, the mysql service will hang.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5959] opened 2022-06-14 01:15 UTC
When running `SELECT NULLIF(1, 1);` and `SELECT NULLIF('a', 'a');`, the mysql service will hang.

_Originally posted by @PsiACE in https://github.com/datafuselabs/databend/issues/5958#issuecomment-1154372938_

**Comment by BohuTANG** [comment] 2022-06-14 01:17
`select ignore( c) from liket` hang on my laptop:
https://github.com/datafuselabs/databend/issues/3915#issuecomment-1152940508

**Comment by sundy-li** [comment] 2022-06-14 01:19
> `select ignore( c) from liket` hang on my laptop: [#3915 (comment)](https://github.com/datafuselabs/databend/issues/3915#issuecomment-1152940508)

I think it's not a bug, because the data is too large to output.

**Comment by TCeason** [comment] 2022-06-14 02:25
I test this case:

```SQL
'root'@mysqldb 10:21:52 [(none)]> set enable_planner_v2 = 1;
Query OK, 0 rows affected (0.03 sec)
Read 0 rows, 0.00 B in 0.002 sec., 0 rows/sec., 0.00 B/sec.

'root'@mysqldb 10:21:54 [(none)]> SELECT NULLIF(1, 1);

```

Not only hang, actually the MySQL session was destroyed.

**Comment by TCeason** [comment] 2022-06-14 02:29
In debug log:

```
2022-06-14T02:27:38.652211Z  INFO do_query{query="SELECT NULLIF(1, 1)"}: databend_query::servers::mysql::mysql_interactive_worker: Normal query: SELECT NULLIF(1, 1)
2022-06-14T02:27:38.652820Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: common_meta_raft_store::state_machine::sm: seq_value: SeqV { seq: 50, meta: Some(KVMeta { expire_at: Some(1655173696) }), data: "[binary]" } now: 1655173658
2022-06-14T02:27:38.653195Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: databend_query::sessions::query_ctx: Create QueryContext
2022-06-14T02:27:38.653453Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: parsing expr    
2022-06-14T02:27:38.653713Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: parsing expr    
2022-06-14T02:27:38.653908Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: prefix: Value(Number("1", false))    
2022-06-14T02:27:38.654098Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: get_next_precedence() Comma    
2022-06-14T02:27:38.654272Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: next precedence: 0    
2022-06-14T02:27:38.654454Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: parsing expr    
2022-06-14T02:27:38.654647Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: prefix: Value(Number("1", false))    
2022-06-14T02:27:38.654879Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: get_next_precedence() RParen    
2022-06-14T02:27:38.655052Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: next precedence: 0    
2022-06-14T02:27:38.655228Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: prefix: Function(Function { name: ObjectName([Ident { value: "NULLIF", quote_style: None }]), params: [], args: [Unnamed(Expr(Value(Number("1", false)))), Unnamed(Expr(Value(Number("1", false))))], over: None, distinct: false })    
2022-06-14T02:27:38.655451Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: get_next_precedence() EOF    
2022-06-14T02:27:38.655624Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}: sqlparser::parser: next precedence: 0    
2022-06-14T02:27:38.660940Z DEBUG do_query{query="SELECT NULLIF(1, 1)"}:exec_query:select_interpreter_v2_execute{ctx.id="04d0e350-d7e0-4e1e-aaab-8b2a3f3b8ffa"}: databend_query::pipelines::new::executor::executor_graph: Create running graph:digraph {
    0 [ label = "system.one" ]
    1 [ label = "ProjectionTransform" ]
    2 [ label = "ProjectionTransform" ]
    3 [ label = "ProjectionTransform" ]
    4 [ label = "ProjectionTransform" ]
    5 [ label = "PullingExecutorSink" ]
    0 -> 1 [ ]
    1 -> 2 [ ]
    2 -> 3 [ ]
    3 -> 4 [ ]
    4 -> 5 [ ]
}

2022-06-14T02:27:38.662039Z DEBUG transform_expression_execute: databend_query::pipelines::transforms::transform_expression_executor: (expression executor) execute, actions: [Input(ActionInput { name: "dummy", return_type: UInt8(UInt8) }), Alias(ActionAlias { name: "\"dummy\"_0", arg_name: "dummy", arg_type: UInt8(UInt8) })]
2022-06-14T02:27:38.662722Z DEBUG transform_expression_execute: databend_query::pipelines::transforms::transform_expression_executor: (expression executor) execute, actions: [Constant(ActionConstant { name: "1", value: 1, data_type: UInt8(UInt8) }), Constant(ActionConstant { name: "NULL", value: NULL, data_type: Null(Null) }), Constant(ActionConstant { name: "true", value: true, data_type: Boolean(Boolean) }), Function(ActionFunction { name: "if(true, NULL, 1)", func_name: "if", return_type: Nullable(Nullable(UInt8)), arg_names: ["true", "NULL", "1"], arg_types: [Boolean(Boolean), Null(Null), UInt8(UInt8)] }), Alias(ActionAlias { name: "\"NULLIF(1, 1)\"_1", arg_name: "if(true, NULL, 1)", arg_type: Nullable(Nullable(UInt8)) })]
2022-06-14T02:27:38.663510Z DEBUG transform_expression_execute: databend_query::pipelines::transforms::transform_expression_executor: (expression executor) execute, actions: [Input(ActionInput { name: "\"NULLIF(1, 1)\"_1", return_type: Nullable(Nullable(UInt8)) })]
2022-06-14T02:27:38.664028Z DEBUG transform_expression_execute: databend_query::pipelines::transforms::transform_expression_executor: (expression executor) execute, actions: [Input(ActionInput { name: "\"NULLIF(1, 1)\"_1", return_type: Nullable(Nullable(UInt8)) }), Alias(ActionAlias { name: "NULLIF(1, 1)", arg_name: "\"NULLIF(1, 1)\"_1", arg_type: Nullable(Nullable(UInt8)) })]
2022-06-14T02:27:38.665032Z  WARN databend_query::pipelines::new::executor::pipeline_pulling_executor: Send finish event error SendError { .. }
2022-06-14T02:27:38.665408Z DEBUG databend_query::sessions::query_ctx: Destroy QueryContext
2022-06-14T02:27:38.665706Z DEBUG common_meta_raft_store::state_machine::sm: seq_value: SeqV { seq: 50, meta: Some(KVMeta { expire_at: Some(1655173696) }), data: "[binary]" } now: 1655173658
2022-06-14T02:27:38.666451Z DEBUG databend_query::sessions::session_ref: Destroy session 7e7b8a7f-1c5a-41b5-8ce6-8418d663be43

```

**Comment by RinChanNOWWW** [comment] 2022-06-14 02:51
`NULLIF(expr1, expr1)` is based on `IF(expr1 = expr2, NULL, expr1)`.

And running

```sql
IF(1 =1, NULL , 1)
```

under planner v2 also hangs:

![image](https://user-images.githubusercontent.com/33975039/173483211-1c69440e-a93e-4817-a2c2-3a3cd953c24e.png)

**Comment by TCeason** [comment] 2022-06-14 02:54
> `NULLIF(expr1, expr1)` is based on `IF(expr1 = expr2, NULL, expr1)`.
> 
> And running
> 
> ```sql
> IF(1 =1, NULL , 1)
> ```
> 
> under planner v2 also hangs:
> 
> ![image](https://user-images.githubusercontent.com/33975039/173483211-1c69440e-a93e-4817-a2c2-3a3cd953c24e.png)

Actually, that is the session was destroyed. And I don't know why this function will cause the client to destroy.

**Comment by sundy-li** [comment] 2022-06-14 02:56
I did not figure out why, cc @leiysky  any suggestions?

**Comment by leiysky** [comment] 2022-06-14 07:34
The root cause of this issue is that if there is an error raised during the serialization of result `DataBlock`s, then mysql handler cannot close the connection for some reasons.

I'm digging with the bug.

**Comment by xudong963** [comment] 2022-06-14 08:59
I have fixed in my newest pr

**Comment by leiysky** [comment] 2022-06-14 09:35
@sundy-li @TCeason 

There are two issues here:
1. As I mentioned above, if some errors are raised here, then the result cannot be returned to mysql client, and the connection won't be closed(which cause the hanging)
https://github.com/datafuselabs/databend/blob/44f74a0b09d70dde8a4a5e642881912af05a00bb/query/src/servers/mysql/mysql_interactive_worker.rs#L196-L199

2. The result column's data type of `IF` function may mismatch with the return type of function object, which may cause the query handler chose a wrong serializer and trigger the issue `1`. The following query will cause hanging with old planner:
```sql
create table t(a int);
select if(true,null,a) from t;
```

I have no idea with 1 now. 

To solve the issue 2, I think it's better to cast the result to return type inside `IF` function.

**Comment by sundy-li** [comment] 2022-06-14 13:05
I'll dig into 2.

**Comment by TCeason** [comment] 2022-06-14 13:29
About `1.` Do you mean:

the func `on_query` will return write_result

https://github.com/datafuselabs/databend/blob/44f74a0b09d70dde8a4a5e642881912af05a00bb/query/src/servers/mysql/mysql_interactive_worker.rs#L206

And in https://github.com/datafuselabs/opensrv/blob/main/mysql/src/lib.rs#L520 will judge this type.

But finally it return a Ok(())

**Closed** 2022-06-23 00:28 UTC
Labels: C-bug, A-query
