### ISSUE TITLE
bug:  distribute insert into memory table query hang 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#4981] opened 2022-04-21 03:59 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

latest

### What's Wrong?

distribute insert into memory table query hang 

### How to Reproduce?

1. start 3 nodes `./scripts/ci/deploy/databend-query-cluster-3-nodes.sh`
2. create memory table:
```
	create table retention_test(date Date, uid INT) Engine = Memory;
```
3. insert:
```
insert into  retention_test select 1, number from numbers(80);  --hang
insert into  retention_test select number + 3, number from numbers(10);  --hang
```

And I can't find any error logs.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhang2014** [comment] 2022-04-21 05:13
Not only in the cluster mode, when a panic occurs in the query, the server will hang, and I will fixes it.

**Comment by wubx** [comment] 2022-05-06 11:12
use sysbench to prepare data:
10 tables 10 threads insert may touch hang

![image](https://user-images.githubusercontent.com/320680/167120813-562312dc-0c95-495c-b190-63c8fff8e126.png)

with  ten minutes still hang.

![image](https://user-images.githubusercontent.com/320680/167120829-386fe867-8f97-4eed-8f1c-8f0a9d3c6201.png)

MySQL [(none)]> select version();
+--------------------------------------------------------------------------+
| @@version()                                                              |
+--------------------------------------------------------------------------+
| 8.0.26--2b2733a-simd(rust-1.61.0-nightly-2022-05-05T16:19:02.657975475Z) |
+--------------------------------------------------------------------------+
1 row in set (0.002 sec)

**Comment by DCjanus** [comment] 2022-05-14 11:32
looks like this issue has been fixed. I can't reproduce in main branch anymore

**Comment by sundy-li** [comment] 2022-05-14 11:37
> looks like this issue has been fixed. I can't reproduce in main branch anymore

It's fixed , but the main problem is that panic occurs inside the async runtime, the main thread will hang.

**Comment by zhang2014** [comment] 2022-07-21 06:40
Can't be reproduced in main branch. Let's close it.

**Closed by zhang2014** 2022-07-21 06:40 UTC
Labels: C-bug
