### ISSUE TITLE
Flaky test: unit test build failure

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#1206] opened 2021-07-28 02:52 UTC
**Summary**
https://github.com/datafuselabs/datafuse/pull/1199/checks?check_run_id=3171838200

**Comment by Xuanwo** [comment] 2021-12-22 06:29
Can't reproduce, and the log is purged.

I'm going to close this issue, please feel free to submit new issues if we meet test failure again.

**Closed by Xuanwo** 2021-12-22 06:29 UTC
