### ISSUE TITLE
bug: streaming load parquet got incomplete results 

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/databend#10647] opened 2023-03-19 01:54 UTC
**Summary**

duckdb can generate tpch datasets in parquet format
```
import duckdb
import pathlib

sf=30
for x in range(0, sf) :
  con=duckdb.connect()
  con.sql('PRAGMA disable_progress_bar;SET preserve_insertion_order=false')
  con.sql(f"CALL dbgen(sf={sf} , children ={sf}, step = {x})") 
  for tbl in ['lineitem'] :
     pathlib.Path(f'./{tbl}').mkdir(parents=True, exist_ok=True) 
     con.sql(f"COPY (SELECT * FROM {tbl}) TO './{tbl}/{x}.parquet' ")
  con.close()
```

streaming load parquet into databend
```
echo "truncate table lineitem" | mysql -uroot -h127.0.0.1 -P3307
insert_sql="insert into lineitem file_format = (type = Parquet)"
p="lineitem.parquet"
curl -s -u root: -XPUT "http://localhost:8000/v1/streaming_load" -H "insert_sql: ${insert_sql}" -F 'upload=@"'$p'"'
echo "select count(1) from lineitem" | mysql -uroot -h127.0.0.1 -P3307

```

results are incomplete.

But `copy into` works fine.

**Comment by akoshchiy** [comment] 2023-06-22 22:54
@sundy-li I think, I've found it. The problem is in the `crossbeam_channel`, which is syncing batches between a `Aligner` and a `DeserializeTransformer`. The channel is buffered, so after closing outputs in the `Aligner`, the `DeserializeTransformer` also closes own outputs, but there is still a buffered data in the channel. The simplest fix is to bound the size of the channel to one, but I'm not sure about any other consequences :)
https://github.com/datafuselabs/databend/blob/80dd387355bbfa5b9f20a49d79b47da151152e3b/src/query/pipeline/sources/src/input_formats/input_pipeline.rs#L280
`
 let (row_batch_tx, row_batch_rx) = crossbeam_channel::bounded(1);
`

**Comment by sundy-li** [comment] 2023-06-23 00:56
> The simplest fix is to bound the size of the channel to one, but I'm not sure about any other consequences

@youngsofun  can help with this?

**Closed** 2023-06-26 08:48 UTC
Labels: C-bug
