### ISSUE TITLE
Bug:  Fail to read parquet files generated by pyarrow 

### ISSUE THREAD

**Issue by alitrack** [datafuselabs/databend#4654] opened 2022-04-01 05:12 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.7.3

### What's Wrong?

I tried insert data to [ontime](https://databend.rs/doc/learn/analyze-ontime-with-databend-on-ec2-and-s3) with parquet format
[ontime2.parquet.zip](https://github.com/datafuselabs/databend/files/8394826/ontime2.parquet.zip)

no matter `disk` or `s3`(minio), both got errors,

```bash
echo curl -H \"insert_sql:insert into ontime format Parquet\" -F  \"upload=@./tmp01.parquet\" -XPUT http://127.0.0.1:8081/v1/streaming_load|bash
```
got 
```
   1: backtrace::capture::Backtrace::new
   2: common_tracing::panic_hook::set_panic_hook::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::slice::index::slice_end_index_len_fail
   9: arrow2::io::parquet::read::deserialize::utils::extend_from_decoder
  10: arrow2::io::parquet::read::deserialize::utils::extend_from_new_page
  11: arrow2::io::parquet::read::deserialize::utils::next
  12: <arrow2::io::parquet::read::deserialize::binary::basic::Iter<O,A,I> as core::iter::traits::iterator::Iterator>::next
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  18: <arrow2::io::parquet::read::row_group::RowGroupDeserializer as core::iter::traits::iterator::Iterator>::next
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
  22: <common_streams::stream_progress::ProgressStream as futures_core::stream::Stream>::poll_next
  23: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
  24: <S as futures_core::stream::TryStream>::try_poll_next
  25: <futures_util::stream::try_stream::try_flatten::TryFlatten<St> as futures_core::stream::Stream>::poll_next
  26: <futures_util::stream::try_stream::try_unfold::TryUnfold<T,F,Fut> as futures_core::stream::Stream>::poll_next
  27: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
  28: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
  29: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  45: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
  46: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  47: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  48: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  49: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  50: tokio::runtime::task::harness::poll_future
  51: tokio::runtime::task::harness::Harness<T,S>::poll
  52: tokio::runtime::thread_pool::worker::Context::run_task
  53: tokio::runtime::thread_pool::worker::run
  54: tokio::runtime::task::raw::poll
  55: std::sys_common::backtrace::__rust_begin_short_backtrace
  56: core::ops::function::FnOnce::call_once{{vtable.shim}}
  57: std::sys::unix::thread::Thread::new::thread_start
  58: __pthread_start
 [3mpanic.file[0m[2m=[0m"/Users/runner/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/b0774c8/src/io/parquet/read/deserialize/utils.rs" [3mpanic.line[0m[2m=[0m35 [3mpanic.column[0m[2m=[0m23

```

```bash
mysql -h127.0.0.1 -uroot -P3307 -e  "copy into ontime from '@my_int_stage' files=('ontime2.parquet') file_format = (type = 'Parquet');"
```

```
[2m2022-04-01T04:48:22.666268Z[0m [32m INFO[0m [2mdatabend_query::interpreters::interpreter_copy[0m[2m:[0m copy file list:["stage/my_int_stage/ontime2.parquet"], pattern:
[2m2022-04-01T04:48:22.666324Z[0m [32m INFO[0m [2mdatabend_query::interpreters::interpreter_copy[0m[2m:[0m copy_one_file_to_table: source plan:ReadDataSourcePlan { source_info: S3StageSource(UserStageInfo { stage_name: "my_int_stage", stage_type: Internal, stage_params: StageParams { storage: S3(StageS3Storage { bucket: "", path: "", credentials_aws_key_id: "", credentials_aws_secret_key: "", encryption_master_key: "" }) }, file_format_options: FileFormatOptions { format: Parquet, skip_header: 0, field_delimiter: "", record_delimiter: "", compression: None }, copy_options: CopyOptions { on_error: None, size_limit: 0 }, comment: "" }), scan_fields: None, parts: [], statistics: Statistics { read_rows: 0, read_bytes: 0, partitions_scanned: 0, partitions_total: 0, is_exact: false }, description: "", tbl_args: None, push_downs: None }
[2m2022-04-01T04:48:23.122343Z[0m [31mERROR[0m [2mcommon_tracing::panic_hook[0m[2m:[0m panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/b0774c8/src/io/parquet/read/deserialize/binary/basic.rs:186:50 [3mbacktrace[0m[2m=[0m   0: backtrace::capture::Backtrace::create
   1: backtrace::capture::Backtrace::new
   2: common_tracing::panic_hook::set_panic_hook::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: arrow2::io::parquet::read::deserialize::utils::next
  10: <arrow2::io::parquet::read::deserialize::binary::basic::Iter<O,A,I> as core::iter::traits::iterator::Iterator>::next
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  16: <arrow2::io::parquet::read::row_group::RowGroupDeserializer as core::iter::traits::iterator::Iterator>::next
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::runtime::task::harness::poll_future
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::thread_pool::worker::Context::run_task
  25: tokio::runtime::thread_pool::worker::run
  26: tokio::runtime::task::raw::poll
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: std::sys::unix::thread::Thread::new::thread_start
  30: __pthread_start
 [3mpanic.file[0m[2m=[0m"/Users/runner/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/b0774c8/src/io/parquet/read/deserialize/binary/basic.rs" [3mpanic.line[0m[2m=[0m186 [3mpanic.column[0m[2m=[0m50

```

### What You Expected?

successfully upload the parquet.

### How to Reproduce?

[ontime2.parquet.zip](https://github.com/datafuselabs/databend/files/8394826/ontime2.parquet.zip)

```sql
CREATE TABLE ontime
(
    Year                            UInt16 NOT NULL,
    Quarter                         UInt8 NOT NULL,
    Month                           UInt8 NOT NULL,
    DayofMonth                      UInt8 NOT NULL,
    DayOfWeek                       UInt8 NOT NULL,
    FlightDate                      Date NOT NULL,
    Reporting_Airline               String NOT NULL,
    DOT_ID_Reporting_Airline        Int32 NOT NULL,
    IATA_CODE_Reporting_Airline     String NOT NULL,
    Tail_Number                     String NOT NULL,
    Flight_Number_Reporting_Airline String NOT NULL,
    OriginAirportID                 Int32 NOT NULL,
    OriginAirportSeqID              Int32 NOT NULL,
    OriginCityMarketID              Int32 NOT NULL,
    Origin                          String NOT NULL,
    OriginCityName                  String NOT NULL,
    OriginState                     String NOT NULL,
    OriginStateFips                 String NOT NULL,
    OriginStateName                 String NOT NULL,
    OriginWac                       Int32 NOT NULL,
    DestAirportID                   Int32 NOT NULL,
    DestAirportSeqID                Int32 NOT NULL,
    DestCityMarketID                Int32 NOT NULL,
    Dest                            String NOT NULL,
    DestCityName                    String NOT NULL,
    DestState                       String NOT NULL,
    DestStateFips                   String NOT NULL,
    DestStateName                   String NOT NULL,
    DestWac                         Int32 NOT NULL,
    CRSDepTime                      Int32 NOT NULL,
    DepTime                         Int32 NOT NULL,
    DepDelay                        Int32 NOT NULL,
    DepDelayMinutes                 Int32 NOT NULL,
    DepDel15                        Int32 NOT NULL,
    DepartureDelayGroups            String NOT NULL,
    DepTimeBlk                      String NOT NULL,
    TaxiOut                         Int32 NOT NULL,
    WheelsOff                       Int32 NOT NULL,
    WheelsOn                        Int32 NOT NULL,
    TaxiIn                          Int32 NOT NULL,
    CRSArrTime                      Int32 NOT NULL,
    ArrTime                         Int32 NOT NULL,
    ArrDelay                        Int32 NOT NULL,
    ArrDelayMinutes                 Int32 NOT NULL,
    ArrDel15                        Int32 NOT NULL,
    ArrivalDelayGroups              Int32 NOT NULL,
    ArrTimeBlk                      String NOT NULL,
    Cancelled                       UInt8 NOT NULL,
    CancellationCode                String NOT NULL,
    Diverted                        UInt8 NOT NULL,
    CRSElapsedTime                  Int32 NOT NULL,
    ActualElapsedTime               Int32 NOT NULL,
    AirTime                         Int32 NOT NULL,
    Flights                         Int32 NOT NULL,
    Distance                        Int32 NOT NULL,
    DistanceGroup                   UInt8 NOT NULL,
    CarrierDelay                    Int32 NOT NULL,
    WeatherDelay                    Int32 NOT NULL,
    NASDelay                        Int32 NOT NULL,
    SecurityDelay                   Int32 NOT NULL,
    LateAircraftDelay               Int32 NOT NULL,
    FirstDepTime                    String NOT NULL,
    TotalAddGTime                   String NOT NULL,
    LongestAddGTime                 String NOT NULL,
    DivAirportLandings              String NOT NULL,
    DivReachedDest                  String NOT NULL,
    DivActualElapsedTime            String NOT NULL,
    DivArrDelay                     String NOT NULL,
    DivDistance                     String NOT NULL,
    Div1Airport                     String NOT NULL,
    Div1AirportID                   Int32 NOT NULL,
    Div1AirportSeqID                Int32 NOT NULL,
    Div1WheelsOn                    String NOT NULL,
    Div1TotalGTime                  String NOT NULL,
    Div1LongestGTime                String NOT NULL,
    Div1WheelsOff                   String NOT NULL,
    Div1TailNum                     String NOT NULL,
    Div2Airport                     String NOT NULL,
    Div2AirportID                   Int32 NOT NULL,
    Div2AirportSeqID                Int32 NOT NULL,
    Div2WheelsOn                    String NOT NULL,
    Div2TotalGTime                  String NOT NULL,
    Div2LongestGTime                String NOT NULL,
    Div2WheelsOff                   String NOT NULL,
    Div2TailNum                     String NOT NULL,
    Div3Airport                     String NOT NULL,
    Div3AirportID                   Int32 NOT NULL,
    Div3AirportSeqID                Int32 NOT NULL,
    Div3WheelsOn                    String NOT NULL,
    Div3TotalGTime                  String NOT NULL,
    Div3LongestGTime                String NOT NULL,
    Div3WheelsOff                   String NOT NULL,
    Div3TailNum                     String NOT NULL,
    Div4Airport                     String NOT NULL,
    Div4AirportID                   Int32 NOT NULL,
    Div4AirportSeqID                Int32 NOT NULL,
    Div4WheelsOn                    String NOT NULL,
    Div4TotalGTime                  String NOT NULL,
    Div4LongestGTime                String NOT NULL,
    Div4WheelsOff                   String NOT NULL,
    Div4TailNum                     String NOT NULL,
    Div5Airport                     String NOT NULL,
    Div5AirportID                   Int32 NOT NULL,
    Div5AirportSeqID                Int32 NOT NULL,
    Div5WheelsOn                    String NOT NULL,
    Div5TotalGTime                  String NOT NULL,
    Div5LongestGTime                String NOT NULL,
    Div5WheelsOff                   String NOT NULL,
    Div5TailNum                     String NOT NULL
);

```

```bash
echo curl -H \"insert_sql:insert into ontime format Parquet\" -F  \"upload=@./ontime2.parquet\" -XPUT http://127.0.0.1:8081/v1/streaming_load|bash
```

```bash
mysql -h127.0.0.1 -uroot -P3307 -e "copy into ontime from '@my_int_stage' files=('ontime2.parquet') file_format = (type = 'Parquet');"

```

### Anything Else?

I tried csv, it is OK, and tried books.parquet example, also ok.

btw, the parquet created by databend can not parsed by  pyarrow , 

```python
import pyarrow.parquet as pq
pq.read_pandas("/usr/local/var/minio/databend/1/4/_b/2fbff1270aec4748941939bdb388be3a_v0.parquet")
```
got issue,

```
OSError: Corrupt Lz4 compressed data.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by sundy-li** [comment] 2022-04-01 09:24
Hello, How did you generate  [ontime2.parquet.zip](https://github.com/datafuselabs/databend/files/8394826/ontime2.parquet.zip)   parquet file?

**Comment by dantengsky** [comment] 2022-04-01 09:44
> btw, the parquet created by databend can not parsed by pyarrow ,
> 
> ~~~
> import pyarrow.parquet as pq
> pq.read_pandas("/usr/local/var/minio/databend/1/4/_b/2fbff1270aec4748941939bdb388be3a_v0.parquet")
> ~~~
> got issue,
> 
> ~~~
> OSError: Corrupt Lz4 compressed data.
> ~~~

Seems that `pyarrow` no longer supports LZ4 (which is replaced by LZ$_RAW)

https://issues.apache.org/jira/browse/PARQUET-2032

and the background

https://lists.apache.org/thread/l15qq12v38w9jnkd6p9mdd11kr0nq3gr

**Comment by alitrack** [comment] 2022-04-01 10:09
> Hello, How did you generate [ontime2.parquet.zip](https://github.com/datafuselabs/databend/files/8394826/ontime2.parquet.zip) parquet file?

pyarrow 6.0.1

**Comment by alitrack** [comment] 2022-04-01 10:34
pyarrow 7.0.0 has the same issue.



> > btw, the parquet created by databend can not parsed by pyarrow ,
> > ```
> > import pyarrow.parquet as pq
> > pq.read_pandas("/usr/local/var/minio/databend/1/4/_b/2fbff1270aec4748941939bdb388be3a_v0.parquet")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > got issue,
> > ```
> > OSError: Corrupt Lz4 compressed data.
> > ```
> 
> ~Seems that `pyarrow` no longer supports LZ4 (which is replaced by LZ4_RAW)~
> 
> Seems that there are some compatibility issues (pyarrow do support LZ4, as the error message indicates clearly)
> 
> https://lists.apache.org/thread/l15qq12v38w9jnkd6p9mdd11kr0nq3gr
> 
> maybe LZ4_RAW should be used
> 
> https://issues.apache.org/jira/browse/PARQUET-2032

from the source [code](https://github.com/apache/arrow/blob/bf18e6e4b5bb6180706b1ba0d597a65a4ce5ca48/cpp/src/arrow/util/compression.cc),  apache arrow should support LZ4, LZ4_FRAME, LZ4_RAW

**Comment by sundy-li** [comment] 2022-04-01 12:24
`pyarrow    7.0.0 `

works in my env:

```
>>> import pyarrow.parquet as pq
>>> c = pq.read_pandas("./ontime2.parquet")
>>> c
pyarrow.Table
Year: int32
Quarter: int32
Month: int32
DayofMonth: int32
DayOfWeek: int32
FlightDate: date32[day]
```

**Comment by alitrack** [comment] 2022-04-01 13:19
@sundy-li  it was created by  pyarrow, does not work with databend.

**Comment by dantengsky** [comment] 2022-04-02 05:53
@alitrack @sundy-li 

Looks like the [comment](https://github.com/datafuselabs/databend/issues/4654#issuecomment-1085689318) message that I've "injected"  mislead you, apologize for that.

That comment is mainly for the following problem :

> btw, the parquet created by databend can not parsed by pyarrow ,
> 
> ~~~
> import pyarrow.parquet as pq
> pq.read_pandas("/usr/local/var/minio/databend/1/4/_b/2fbff1270aec4748941939bdb388be3a_v0.parquet")
> ~~~
> got issue,
> 
> ~~~
> OSError: Corrupt Lz4 compressed data.
> ~~~

I can confirm that parquet file written by `parquet2 10.0.3`, with compression option `Compression::Lz4Raw`, is readable for `pyarrow 7.0.0`. 

Unfortunately,  databend uses an older version of parquet2 which does not support `Compression::Lz4Raw` yet.

Tried to bump the version of parquet2, but failed, there are some other dependency issues there.

**Comment by BohuTANG** [comment] 2022-04-02 09:16
There are two questions here, it looks better we disscuss them separately:
1. import parquet file panic
2. fuse engine parquet file can not read by pyarrow

For the 2), @dantengsky found the root cause #4668 
For the 1), is it related to the 2)?

**Comment by dantengsky** [comment] 2022-04-02 13:04
>  For the 1), is it related to the 2)?

@BohuTANG @sundy-li  

For your reference:

After digging into the `1)` (exceptions when databend reading parquet generated by pyarrow) a little bit: 

It seems not directly related to `2)` (pyarrow do not recognize the parquet generated by databend). 

in case `1)`,  arrow2 panics at 

https://github.com/datafuse-extras/arrow2/blob/b0774c8a9b4819fef513934a6ed665b7df606315/src/io/parquet/read/deserialize/binary/basic.rs#L184-L186

~~~rust
impl<'a, O: Offset> utils::Decoder<'a, &'a [u8], Binary<O>> for BinaryDecoder<O> {
    type State = State<'a>;
   
    fn build_state(&self, page: &'a DataPage) -> Result<Self::State> {
        ...

        match (page.encoding(), page.dictionary_page(), is_optional) {
            ....
            (Encoding::PlainDictionary | Encoding::RleDictionary, Some(dict), true) => {
                Ok(State::OptionalDictionary(OptionalDictionary::new(
                    page,
                    dict.as_any().downcast_ref().unwrap(),
~~~                    
                    
at the time of panic, the `dict` that captured by pattern match is of type `PrimitivePageDict`, which is unable to be cast to `BinaryPageDict` ...

---------------

https://github.com/datafuse-extras/arrow2/blob/b0774c8a9b4819fef513934a6ed665b7df606315/src/io/parquet/read/deserialize/binary/basic.rs#L93-L111

~~~rust
struct OptionalDictionary<'a> {
    values: hybrid_rle::HybridRleDecoder<'a>,
    validity: OptionalPageValidity<'a>,
    dict: &'a BinaryPageDict,
}

impl<'a> OptionalDictionary<'a> {
    fn new(page: &'a DataPage, dict: &'a BinaryPageDict) -> Self {
        .....
    }
}
~~~

**Comment by Xuanwo** [comment] 2022-04-07 23:58
@dantengsky Can you help update the issue title? I believe "curl: (52) Empty reply" is not the root cause.

**Comment by BohuTANG** [comment] 2022-04-23 00:55
Fixed in https://github.com/datafuselabs/databend/pull/4726, let's close.

**Closed by BohuTANG** 2022-04-23 00:55 UTC
Labels: C-bug, A-query
