### ISSUE TITLE
feat: not show SNAPSHOT_LOCATION when show create table

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#10132] opened 2023-02-20 06:34 UTC
**Summary**

```
show create table t1;
CREATE TABLE t1` (  `name` VARCHAR) ENGINE=FUSE SNAPSHOT_LOCATION='584180/584234/_ss/523697ab87b140e68076a288b8a16494_v2.json'
```

If the user COPY and create a new table, `SNAPSHOT_LOCATION` will break the table, we should ignore this option with a new setting: `show_option_in_show_create_table`, default is false.

**Comment by xinlifoobar** [comment] 2023-02-21 11:22
May I pick this as the first issue? Some followups:
- If 2 tables use the same SNAPSHOT_LOCATION, then they are actually referencing the same table, is this just by design?
- Shall the settings be a `QueryConfig`, just confused about the settings sections.

**Comment by BohuTANG** [comment] 2023-02-21 12:02
> * If 2 tables use the same SNAPSHOT_LOCATION, then they are actually referencing the same table, is this just by design?

Yes.

> * Shall the settings be a `QueryConfig`, just confused about the settings sections.

No, you can reference this PR: how to add a new settings https://github.com/datafuselabs/databend/pull/9406

**Comment by xinlifoobar** [comment] 2023-02-22 01:33
Thanks. Based on above, the `show_option_in_show_create_table` should be a boolean value, instead of a list. How about creating a new settings named like `hide_option_in_show_create_table` and the value is a comma-separated list default to SNAPSHOT_LOCATION? This way is act as https://github.com/datafuselabs/databend/blob/cffa03811edc4ab88c852d78f7d065cd0903788e/src/query/storages/common/table-meta/src/table/table_keys.rs.

**Comment by BohuTANG** [comment] 2023-02-22 01:47
> How about creating a new setting named hide_option_in_show_create_table

Good. We can make the `hide_option_in_show_create_table ` default to false. 

> the value is a comma-separated list default to SNAPSHOT_LOCATION

We should hide all the options lists in the table_keys.rs

**Comment by xinlifoobar** [comment] 2023-02-22 11:24
This PR expresses my idea regards hide_options_in_show_create_table to introduce a comma-separated list... I somehow get the idea to use one boolean to control all options. If this is not common practice plz let me know...

**Comment by johnhaxx7** [comment] 2023-02-27 05:35
ping for close, thanks!

**Comment by xinlifoobar** [comment] 2023-02-27 06:14
Hi @johnhaxx7, it seems I don't have perms to close. Any groups needs to join?

**Comment by sundy-li** [comment] 2023-02-27 06:51
You can use `close #xxx ` in the pr, if pr is merged, this issue will be closed.

**Closed** 2023-02-27 06:51 UTC
Labels: C-feature, good first issue
